### ISSUE TITLE
The 9.0.4 release in pypi isn't tagged in git

### ISSUE THREAD

**Issue by nullr0ute** [jfhbrook/pyee#112]
The pyee release in pypi isn't tagged in github

**Comment by jfhbrook** [comment]
just pushed the tag. apologies!

but I have to know: ...people use the tags? I mostly do them out of old habits, rather than any specific ask from users.

**Comment by nullr0ute** [comment]
It's very useful for audit, to know what is in the associated release elsewhere, such as on pypi, especially for things like CVEs and response management.
