### ISSUE TITLE
RFE: is it possible to start making github releases?🤔

### ISSUE THREAD

**Issue by kloczek** [jfhbrook/pyee#129]
Is it possible next time on release new version make the github release to have entry on https://github.com/jfhbrook/pyee/releases? 🤔

I'm asking because only on make gh release is spread notification about new release to those who have set watch->releases.
My automation process those notification trying make preliminary automated upgrade of building packages which allow save some time on maintaining packaging procedures.

More about gh releases is possible to find on
https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository
https://github.com/marketplace/actions/github-release
https://pgjones.dev/blog/trusted-plublishing-2023/

**Comment by jfhbrook** [comment]
I made a PR:

https://github.com/jfhbrook/pyee/pull/138

It needs review and I need to decide if I'm OK changing the tag format, but otherwise I think this will work. It's pushed for perusal, and otherwise I'll review and pull it in when I do a future pyee release.

**Comment by jfhbrook** [comment]
I'm now making github releases and publishing to pypi with an action:

https://github.com/jfhbrook/pyee/actions/runs/6972654612

The initial release using this feature is here:

https://github.com/jfhbrook/pyee/releases/tag/v11.1.0

Feel free to kick the tires on it. Let me know if you'd like something different and I can see what's possible.

**Comment by kloczek** [comment]
Yep .. it works 👎 
Thank you 😄
