### ISSUE TITLE
ImportError: cannot import name 'BaseEventEmitter' from 'pyee'

### ISSUE THREAD

**Issue by diwap** [jfhbrook/pyee#163]
`(/usr/local/lib/python3.8/dist-packages/pyee/__init__.py)`

Issue with version: 12.0.0

Works fine with version that I initially used i.e. `11.1.0`

**Comment by jfhbrook** [comment]
That import has been deprecated for some time and was removed in 12.0. Try `from pyee.base import EvebtEmitter`.
