### ISSUE TITLE
ImportError: cannot import name 'AsyncIOEventEmitter' from 'pyee' 

### ISSUE THREAD

**Issue by eolmsteadbeyondtrust** [jfhbrook/pyee#166]
Currently using python 3.11.10

Getting the following error

    from pyee import AsyncIOEventEmitter
ImportError: cannot import name 'AsyncIOEventEmitter' from 'pyee' 

have
pyee==12.0.0

**Comment by jfhbrook** [comment]
That import has been deprecated for years and was removed in *I believe* v12. Either import `pyee.asyncio.AsyncIOEventEmitter` or downgrade pyee to an earlier version.

**Comment by eolmsteadbeyondtrust** [comment]
Thanks, I'll try both and see.
