### ISSUE TITLE
Some cannot fetch data using asynchronous

### ISSUE THREAD

**Issue by IQZZ020501** [jfhbrook/pyee#172]
![image](https://github.com/user-attachments/assets/65d145d7-2e6e-408c-bc3e-060b6eadd558)

![image](https://github.com/user-attachments/assets/d9769857-656f-41b9-945a-71337fd47180)

Why can't scan event method get value after using async, but it can when not used? Verification_code events are always asynchronous.

**Comment by jfhbrook** [comment]
My initial guess is that you need to call:

```py
work.on('scan', scan_event)
work.on('verification_code', lambda ...
...
```

`EventEmitter#on` doesn't return `Self`, it returns the callback.

**Comment by IQZZ020501** [comment]
> My guess is that you need to call:
> 
> ```python
> work.on('scan', scan_event)
> work.on('verification_code', lambda ...
> ...
> ```
> 
> `EventEmitter#on` doesn't return `Self`, it returns the callback.

I inherited AsyncIOEventEmitter and rewritten the on method to return Self.
![image](https://github.com/user-attachments/assets/7a4b8b53-f6d6-4776-b62e-e2b6a2e7ea04)

This is my test class:
![image](https://github.com/user-attachments/assets/d8a2531e-713d-462f-b9ad-a2888c756f1e)

This problem has been solved, and it is not the problem of this module. Sorry to disturb you.

**Comment by IQZZ020501** [comment]
> What are you seeing? Do you have a stack trace? Does nothing happen?
> 
> I love your Spongebob, by the way.

Thank you for liking it, this picture is for you
![pycharm壁纸](https://github.com/user-attachments/assets/c189f90c-77d8-4ba2-b6ef-95e23a85b003)
