### ISSUE TITLE
Installation seems to fail on OSX Python 3.6

### ISSUE THREAD

**Issue by gappleto97** [jfhbrook/pyee#34]
https://travis-ci.org/p2p-today/p2p-project/jobs/200988029

I'm not sure if this is because of the build script or the package itself. I'm trying to investigate now, but I figured I'd bring this to your attention in case it turns out to actually be something.

**Comment by gappleto97** [comment]
My gut reaction is that uploading a universal wheel to pypi would probably fix this, but I'm not certain.

**Comment by jfhbrook** [comment]
shouldn't need a wheel if there's no compiled code, right?

**Comment by jfhbrook** [comment]
From here it looks like pypi had an ssl issue that coincidentally started right after pyee's child deps started downloading (vcversioner failed to download, etc)

**Comment by gappleto97** [comment]
It looks that way, but it's consistently failing at the same place, no matter how often I rerun it (3 times now).

That makes me think something else is going on.

**Comment by jfhbrook** [comment]
Alright, well if it helps https://github.com/jfhbrook/pyee/blob/master/Makefile#L5-L11 this is how I'm doing packaging

**Comment by gappleto97** [comment]
Surprisingly, #35 seems to have fixed it. Huh.

https://travis-ci.org/p2p-today/p2p-project/jobs/200999072

**Comment by jfhbrook** [comment]
huh.
