### ISSUE TITLE
Async test for v2.7

### ISSUE THREAD

**Issue by maxime-helen-sb** [jfhbrook/pyee#36]
I read from Travis:
- 11 tests passed on 2.7
- 15 tests passed on 3.0.3

Does it mean v2.7 is half supported? Do you have ideas how to test events asynchronously with 2.7?

Thanks!

**Comment by jfhbrook** [comment]
asyncio tests don't run on 2.7 because `async def` is a syntax error in pythons less than 3.5. This functionality should also work against 3.4 generator-based coroutines, but that functionality is untested.

As far as I know, 2.7 doesn't support asyncio or coroutines at all.

This doesn't mean this library is gimped in 2.7. It works just fine wrapping synchronous functions, which can be used to fire asynchronous actions. This is largely what you'd have to do *anyway*; wrapping async defs is just sugar.

**Comment by jfhbrook** [comment]
Without coroutine support, this library is pretty much a straight port of a subset of functionality from nodejs's EventEmitter class; you can find numerous examples of its use in server side javascript land. The idioms for kicking off async actions in python tend to differ (deferreds/futures, etc) but the gist of it is the same.

**Comment by maxime-helen-sb** [comment]
I am aware of emit emitter node js world. IMHO synchronous tests don't really make sense for event driven approach as it covers 1% of functionalities. The whole interest is to call asynchronously a callback upon an event trigger.

**Comment by jfhbrook** [comment]
I think maybe you misunderstand what "synchronous" means here.

You can emit an event whenever you want--that event can be *fired* "asynchronously" insofar as a scheduled action can trigger an event.

However, the registered listener function is called on the same tick that .emit is called, and the argument to .on is a fire-and-forget function that's unaware of coroutines or futures (in python2). It's in this matter that EEs (both in node and in pyee) are synchronous.

Compare to Twisted deferreds, which are *also* completely synchronous in this regard, and yet are used extensively in asynchronous programming.

I haven't tested this library against tornado specifically, so I don't know what kind of issues/behaviors you are running into. The test coverage for 2.7 should at this point be fairly comprehensive in terms of things you can actually do in 2.7, but if there are specific scenarios you are running into problems with, I would be glad to look, and adjust accordingly.

**Comment by jfhbrook** [comment]
In particular, I would like to see the tornado code you've written.

**Comment by maxime-helen-sb** [comment]
I understand better now, I was wrong. Thank you for your explanations!
