### ISSUE TITLE
once listeners arn't awaited

### ISSUE THREAD

**Issue by Zwork101** [jfhbrook/pyee#37]
I have a listener that's a coroutine, and it's a once event. However, it isn't awaited, hence it doesn't run.

**Comment by jfhbrook** [comment]
Can you submit a reproducing example? That will help (eventually) fix this.

**Comment by jfhbrook** [comment]
Like you're right, once definitely needs some coroutine detection, and I can probably add that over my holiday break, but something I can adopt into a test will ensure that I meet your use case

**Comment by jfhbrook** [comment]
Fix published under 4.0.1.

Thanks!
