### ISSUE TITLE
All callbacks to the same event must take similar signature

### ISSUE THREAD

**Issue by andersea** [jfhbrook/pyee#45]
This is somewhat of an inconvinience. Obviously this is due to python being stricter about function signatures than javascript is.

Take the following example:

    from pyee import EventEmitter

    def takes_one(arg1):
        print(arg1)

    def takes_two(arg1, arg2):
        print(arg1, arg2)

    ee = EventEmitter()

    ee.on('a', takes_one)
    ee.on('a', takes_two)

    ee.emit('a', 'something', 'another')

This would be fine in javascript but results in a TypeError in python.

For me the most convenient would be that extra arguments was simply dropped when calling functions that takes fewer arguments.

The other case where you expect more arguments than is emitted is not as relevant, as you should know the number of possible arguments that an event can emit.

Or we could just live with it and require identical signatures?

**Comment by andersea** [comment]
This would work:

    from inspect import getargspec

    def emit(self, event, *args, **kwargs):
        #...
        try:
            result = f(*args, **kwargs)
        except TypeError:
            result = f(*args[:len(getargspec(f).args)], **kwargs)

`getargspec` is deprecated in python 3.0

**Comment by jfhbrook** [comment]
I have no plans to implement this. If you want variable arguments, use *args and **kwargs, and/or default args.

Cheers!
