### ISSUE TITLE
[question] recommended documentation method

### ISSUE THREAD

**Issue by jlaine** [jfhbrook/pyee#48]
Hi!

First of all thanks for pyee and for making it asyncio-friendly with support for coroutines!

I am using pyee for `aiortc`, my Python/asyncio implementation of WebRTC . I was wondering whether you have a recommendation on how to document the events an object can emit?

**Comment by jfhbrook** [comment]
Not specifically - I've detailed this in my own stuff inside the __init__ doctring for my subclass before, but I wouldn't go so far as to call that a rec.

**Comment by jlaine** [comment]
Thanks for your answer, I might go the same way.
