### ISSUE TITLE
adding an emit_async() to AsyncIOEventEmitter

### ISSUE THREAD

**Issue by nurettin** [jfhbrook/pyee#63]
Everything would remain the same with emit(), but it would await any coroutines. My use case is that I need to know when all the registered coroutines are finished. Does it make sense to add it?

**Comment by jfhbrook** [comment]
I don't think it makes sense to be able to run `await ee.emit_async('some_event')` - the API is intentionally fire-and-forget.

My suggestion would be to either emit a "finished" event of some kind and then use a counter to track when they all return, or use a different abstraction that better supports your use case.

Cheers!
