### ISSUE TITLE
pytest-runner is deprecated upstream due to e.g. breaking some Pip features

### ISSUE THREAD

**Issue by strugee** [jfhbrook/pyee#82]
See https://github.com/pytest-dev/pytest-runner#deprecation-notice. (Context: this is breaking some packaging work I'm doing that relies on said Pip features.)

**Comment by jfhbrook** [comment]
Happy to take a merge request but I'm unlikely to get to this within the next few weeks.

**Comment by jfhbrook** [comment]
I have a fix, alongside some other things with the dev workflow that were bothering me, here:

https://github.com/jfhbrook/pyee/pull/83

I'll merge and publish this later today, I just want to let it settle since I don't have anyone to code review me.

**Comment by jfhbrook** [comment]
Fix published as v8.2.1. Cheers!

**Comment by strugee** [comment]
Wow, awesome! Thanks @jfhbrook 🎉
