### ISSUE TITLE
Emit can be error

### ISSUE THREAD

**Issue by leirons** [jfhbrook/pyee#95]
Sorry for my english..

```
from pyee import EventEmitter

ee = EventEmitter()

ee.emit('error')
```

It will be "Uncaught, unspecified 'error' event."
But - ee.emit('esadasdsadsa') wont

check for event = error, but instead of error there will be a generated hash with a key, or can it somehow be done differently?

Or it's okay?

**Comment by jfhbrook** [comment]
I don't follow. I don't think emitting a non-error event without data is a bug.
